### PR TITLE
Fix anonymous function edge cases

### LINKED ISSUE #185: Splitdef errors on anonymous function with a single varargs argument
`splitdef` fails with an assertion on an anonymous function with a single varargs argument:

```julia
julia> splitdef(Meta.parse(" (args...) -> 0 "))
ERROR: ArgumentError: Not a function definition: :(args...->begin
          #= none:1 =#
          0
      end)
Stacktrace:
 [1] splitdef(fdef::Expr)
   @ MacroTools ~/.julia/packages/MacroTools/PP9IQ/src/utils.jl:317
```

Either adding another argument or using the long form of the definition is fine:

```julia
julia> splitdef(Meta.parse(" (x, args...) -> 0 "))
Dict{Symbol, Any} with 4 entries:
  :args        => Any[:x, :(args...)]
  :body        => quote…
  :kwargs      => Any[]
  :whereparams => ()

julia> splitdef(Meta.parse(" function f(args...) 0 end "))
Dict{Symbol, Any} with 5 entries:
  :name        => :f
  :args        => Any[:(args...)]
  :kwargs      => Any[]
  :body        => quote…
  :whereparams => ()
```

### LINKED ISSUE #209: Incorrect capture of anonymous function with typed arguments
This is Julia 1.11:

```julia
julia> using MacroTools: splitdef

julia> splitdef(:((a::Int; b=2) -> a + b))
ERROR: AssertionError: Not a function definition: begin
        a::Int
        #= REPL[3]:1 =#
        b = 2
    end->begin
        #= REPL[3]:1 =#
        a + b
    end
Stacktrace:
 [1] splitdef(fdef::Expr)
   @ MacroTools ~/.julia/packages/MacroTools/CJmbb/src/utils.jl:317
 [2] top-level scope
   @ REPL[3]:1
```

### PR DESCRIPTION
**Pull request by MilesCranmer**
This fixes a few classes of anonymous functions that could not be parsed before. @cstjean do you think you could review this? I really need this patch to address some major bugs for BorrowChecker.jl and DispatchDoctor.jl, which both depend on MacroTools.jl for function parsing.

This Fixes #209 Fixes #185 

## More notes

Here are some functions that could not be parsed with `splitdef` before this change, but now work:

- `(a::Int; b=2) -> 1`
- `(args...) -> 1`
- `(arg; kws...) -> 1`

All of these functions hit the error

```julia
ERROR: AssertionError: Not a function definition: begin
```

but now they can parse fine:

```julia
julia> splitdef(quote; (a::Int; b=2) -> 1; end)
Dict{Symbol, Any} with 4 entries:
  :args        => Any[:(a::Int)]
  :body        => quote…
  :kwargs      => Any[:(b = 2)]
  :whereparams => ()

julia> splitdef(quote; (args...) -> 1; end)
Dict{Symbol, Any} with 4 entries:
  :args        => Any[:(args...)]
  :body        => quote…
  :kwargs      => Any[]
  :whereparams => ()

julia> splitdef(quote; (arg; kws...) -> 1; end)
Dict{Symbol, Any} with 4 entries:
  :args        => Any[:arg]
  :body        => quote…
  :kwargs      => Any[:(kws...)]
  :whereparams => ()
```

I've verified 100% test coverage of the code diff. I've also verified all the existing tests pass.

## PR Checklist

- [x] Tests are added
- [x] Documentation, if applicable

### CODE REVIEW

File: src/utils.jl [hunk 1]
```diff
@@ -259,7 +259,34 @@ isshortdef(ex) = (@capture(ex, (fcall_ = body_)) &&
...
   if @capture(ex, (arg_ -> body_))
-    Expr(:function, arg isa Symbol ? :($arg,) : arg, body)
+
+    if isexpr(arg, :tuple) && length(arg.args) == 1 && isexpr(arg.args[1], :parameters)
+      # Special case (; kws...) ->
+      fcall = Expr(:tuple, arg.args[1])
+
+      Expr(:function, fcall, body)
+    elseif isexpr(arg, :block) && any(a -> isexpr(a, :...) || isexpr(a, :(=)) || isexpr(a, :kw), arg.args)
+      # Has keywords in a block
```
Comment (cstjean) [inline src/utils.jl:269]: Sorry, I don't understand what this `elseif` branch is doing. What are "keywords in a block"? Can you give an example?

**Review by cstjean — APPROVED** [review]
Great PR, thanks!

File: src/utils.jl (hunk 1 above)
Comment (MilesCranmer) [reply src/utils.jl:269]: Sure; take a look at the AST of this closure: `dump(quote; (a::Int; b=2) -> a+b; end)`

**Comment by cstjean** [comment]
I'm at work, so sorry that I cannot investigate it in depth, but

```julia
julia> ff = eval( longdef(:((a::Int; b=2) -> a + b)))
#26 (generic function with 1 method)

julia> ff(2, b=11)
13

julia> longdef(:((a::Int; b=2) -> a + b))
:(function a::Int, #= REPL[32]:1 =#, b = 2      # weird
      #= REPL[32]:1 =#
      a + b
  end)
```
While `longdef1` returns a weird expression (at least, that prints weirdly), it is nevertheless handled correctly as a function by `eval`. I'd be interested to know if the weird expression is an acceptable Julia `Expr` (then we should file an isse that it's not printed correctly), or if it just passes accidentally. If it is correct, then the correct fix would be to change

```julia
  @assert(@capture(longdef1(fdef),
                   function (fcall_ | fcall_) body_ end),
          "Not a function definition: $fdef")
```

instead of `longdef1`. It's a wonky `@capture` statement anyway.

If you're in a rush, I'll be happy to oblige and merge as is, though. Would you prefer that? This PR is a clear improvement.

**Comment by MilesCranmer** [comment]
I think given that these are currently not parsed correctly at all, it’s probably better to go with it to fix the bugs, and then polish things later. What do you think?

**Comment by cstjean** [comment]
I'm a bit torn; if the current `longdef` is correct, then the extra code in this PR is unnecessary and it can  be fixed more simply in `splitdef`. 

But if `longdef` is incorrect, then we should definitely merge this. Hopefully we get an answer on discourse. 

I'll try to merge either this PR or some other fix by tomorrow.

**Comment by cstjean** [comment]
I would tend to agree with [Sukera's post](https://discourse.julialang.org/t/function-definition-expr-that-prints-incorrectly-but-evals-correctly/128038/2), that it's a printing problem, but the expression is fundamentally correct Julia. 

MacroTools is a fundamental package, and the expression returned from `longdef` is typically further processed, so I am worried that this PR might break some macro code downstream. I didn't find the time to push it yesterday, but I really want to see if there isn't a simpler `splitdef` fix that passes all the tests in this PR. Sorry for the delay!

**Comment by MilesCranmer** [comment]
That is a fair point. But I would push back and make the point that: if Julia _itself_ doesn't correctly print the output of longdef for this subtle parsing edgecase (which results in bugs #209 and #185), then there is an extremely low probability that someone's code is correctly handling this.

Worst case, it does, it gets reported, and then just revert the change. But I think it's better to worry about known and reported bugs (#209 #185) than theoretical low-probability bugs due to someone possibly making use of an incorrect output that even Julia doesn't handle.

Note that this `:block` format generated by MacroTools seems to only be done for one keyword. Once it is two keywords, that issue goes away:

```julia
julia> longdef(:((a::Int; b=2) -> a+b+c)) |> dump
Expr
  head: Symbol function
  args: Array{Any}((2,))
    1: Expr
      head: Symbol block
      args: Array{Any}((3,))
        1: Expr
          head: Symbol ::
          args: Array{Any}((2,))
            1: Symbol a
            2: Symbol Int
        2: LineNumberNode
          line: Int64 1
          file: Symbol REPL[14]
        3: Expr
          head: Symbol =
          args: Array{Any}((2,))
            1: Symbol b
            2: Int64 2
    2: Expr
      head: Symbol block
      args: Array{Any}((2,))
        1: LineNumberNode
          line: Int64 1
          file: Symbol REPL[14]
        2: Expr
          head: Symbol call
          args: Array{Any}((4,))
            1: Symbol +
            2: Symbol a
            3: Symbol b
            4: Symbol c

julia> longdef(:((a::Int; b=2, c=3) -> a+b+c)) |> dump
Expr
  head: Symbol function
  args: Array{Any}((2,))
    1: Expr
      head: Symbol tuple
      args: Array{Any}((2,))
        1: Expr
          head: Symbol parameters
          args: Array{Any}((2,))
            1: Expr
              head: Symbol kw
              args: Array{Any}((2,))
                1: Symbol b
                2: Int64 2
            2: Expr
              head: Symbol kw
              args: Array{Any}((2,))
                1: Symbol c
                2: Int64 3
        2: Expr
          head: Symbol ::
          args: Array{Any}((2,))
            1: Symbol a
            2: Symbol Int
    2: Expr
      head: Symbol block
      args: Array{Any}((2,))
        1: LineNumberNode
          line: Int64 1
          file: Symbol REPL[13]
        2: Expr
          head: Symbol call
          args: Array{Any}((4,))
            1: Symbol +
            2: Symbol a
            3: Symbol b
            4: Symbol c
```

So only if someone is handling the single arg case for `longdef` would they have such an issue. But since there has been no such report of this weird edgecase, I'm assuming nobody does have it.

**Comment by MilesCranmer** [comment]
Thinking more about this, I'm assuming it's actually more often that people will assume the second `:parameters` form. There could be a bunch of latent bugs out there because someone only wrote their code to handle the `:parameters` form, and just hasn't yet encountered the rare `:block` case. (I feel like it's rare to have a single keyword. Either you have have several keywords, or zero.)

**Comment by cstjean** [comment]
> Note that this :block format generated by MacroTools seems to only be done for one keyword. Once it is two keywords, that issue goes away:

> Thinking more about this, I'm assuming it's actually more often that people will assume the second :parameters form. There could be a bunch of latent bugs out there because someone only wrote their code to handle the :parameters form, and just hasn't yet encountered the rare :block case.

Those are good arguments, I'm sold. If `longdef`'s use case is "I don't want to explicitly deal with the short-form AST", then it makes sense to standardize the `longdef` output as much as possible. Thank you for the PR!
